version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: gcs-postgres
    environment:
      POSTGRES_DB: gcsdb
      POSTGRES_USER: gcsuser
      POSTGRES_PASSWORD: gcspassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gcs-network

  gcs-microservico-java:
    build: .
    container_name: gcs-microservico-java
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gcsdb
      SPRING_DATASOURCE_USERNAME: gcsuser
      SPRING_DATASOURCE_PASSWORD: gcspassword
    depends_on:
      - postgres
    networks:
      - gcs-network

volumes:
  pgdata:

networks:
  gcs-network:
